name: push-docker-image

on:
  push:
    tags:
      - "v[0-9]+.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency: push-docker-image
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ github.repository }}:latest, ${{ github.repository }}:${{ github.ref_name }}
